"""Tests for `scripts/site_metrics.py` (#177): a small repo with known counts
and a fake `gh` that serves merged PRs and logs how it was called.

Run: python3 -m unittest discover -s tests -v
"""
from __future__ import annotations

import json
import os
import stat
import subprocess
import sys
import tempfile
import unittest
from datetime import date

SCRIPTS = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "scripts")
SCRIPT = os.path.join(SCRIPTS, "site_metrics.py")
sys.path.insert(0, SCRIPTS)
sys.dont_write_bytecode = True
import site_metrics  # noqa: E402

FAKE_GH = '''#!/usr/bin/env python3
import json, os, sys
with open(os.environ["FAKE_GH_LOG"], "a") as f:
    f.write(json.dumps(sys.argv[1:]) + "\\n")
if os.environ.get("FAKE_GH_FAIL"):
    sys.exit(1)
with open(os.environ["FAKE_GH_DATA"]) as f:
    prs = json.load(f)
args = sys.argv[1:]
search = args[args.index("--search") + 1] if "--search" in args else ""
if search.startswith("merged:>="):
    prs = [p for p in prs if p["mergedAt"][:10] >= search[len("merged:>="):]]
print(json.dumps(prs))
'''


def write(path: str, text: str) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write(text)


def pr(number: int, lines: int, merged: str) -> dict:
    return {"number": number, "additions": lines - lines // 4, "deletions": lines // 4, "mergedAt": merged}


class SiteMetricsTests(unittest.TestCase):
    def setUp(self) -> None:
        self.tmp = tempfile.TemporaryDirectory()
        self.root = os.path.join(self.tmp.name, "repo")
        r = self.root
        write(f"{r}/CLAUDE_LAWS.md", "# Laws\n\n1. **One.** x\n\n2. **Two.** y\n\n2a. **Two a.** z\n\n    3. **Nested.** n\n")
        write(f"{r}/CLAUDE.md", "rules " * 100)
        write(f"{r}/skills/a/SKILL.md", "a")
        write(f"{r}/skills/b/SKILL.md", "b")
        write(f"{r}/skills/c/notes.md", "no SKILL.md")
        write(f"{r}/agents/x.md", "x")
        write(f"{r}/agents/y.md", "y")
        write(f"{r}/agents/readme.txt", "not an agent")
        write(f"{r}/knowledge/GUIDE.md", "g")
        write(f"{r}/knowledge/PATTERNS.example.md", "template")
        write(f"{r}/tests/test_x.py", "class T:\n    def test_a(self): ...\n    def test_b(self): ...\ndef test_c(): ...\n")
        write(f"{r}/tests/helper.py", "def test_not_counted(): ...\n")
        git = ["git", "-c", "user.name=Test", "-c", "user.email=test@example.com"]
        subprocess.run(["git", "init", "-q", r], check=True)
        subprocess.run(git + ["-C", r, "add", "-A"], check=True)
        subprocess.run(git + ["-C", r, "commit", "-q", "-m", "chore: init"], check=True)
        for tag in ("v1.0.0", "v1.1.0", "v1.1.0-rc1", "other"):
            subprocess.run(["git", "-C", r, "tag", tag], check=True)

        self.gh = os.path.join(self.tmp.name, "gh")
        write(self.gh, FAKE_GH)
        os.chmod(self.gh, os.stat(self.gh).st_mode | stat.S_IEXEC)
        self.data = os.path.join(self.tmp.name, "prs.json")
        self.log = os.path.join(self.tmp.name, "gh.log")
        self.serve([pr(1, 100, "2026-10-01T10:00:00Z"), pr(2, 300, "2026-10-02T10:00:00Z"),
                    pr(3, 800, "2026-10-03T10:00:00Z")])
        self.env = {**os.environ, "FAKE_GH_LOG": self.log, "FAKE_GH_DATA": self.data}

    def tearDown(self) -> None:
        self.tmp.cleanup()

    def serve(self, prs: list[dict]) -> None:
        with open(self.data, "w") as f:
            json.dump(prs, f)

    def run_script(self, today: str = "2026-10-07", **env: str) -> subprocess.CompletedProcess:
        return subprocess.run(
            [sys.executable, SCRIPT, "--root", self.root, "--gh", self.gh, "--today", today],
            capture_output=True, text=True, env={**self.env, **env},
        )

    def numbers(self) -> dict:
        with open(os.path.join(self.root, "site", "data.js")) as f:
            text = f.read()
        self.assertTrue(text.startswith("// Generated by scripts/site_metrics.py"))
        return json.loads(text[text.index("{"):text.rindex("}") + 1])["numbers"]

    def gh_calls(self) -> list[list[str]]:
        with open(self.log) as f:
            return [json.loads(line) for line in f]

    def test_counts_come_from_the_repo(self) -> None:
        self.assertEqual(self.run_script().returncode, 0)
        values = {name: n["value"] for name, n in self.numbers().items()}
        self.assertEqual(values["releases"], 2)  # vX.Y.Z only
        self.assertEqual(values["laws"], 2)  # top-level numbered laws, not 2a or a nested list
        self.assertEqual((values["skills"], values["agents"], values["guides"]), (2, 2, 1))
        self.assertEqual(values["tests"], 3)  # test_*.py files only
        self.assertGreater(values["rules_tokens"], 0)

    def test_pr_numbers(self) -> None:
        self.run_script()
        values = {name: n["value"] for name, n in self.numbers().items()}
        self.assertEqual(values["prs_merged"], 3)
        self.assertEqual(values["median_pr_lines"], 300)
        self.assertEqual(values["prs_within_400"], 67)  # 2 of 3, as a whole percent

    def test_every_number_has_its_date(self) -> None:
        self.run_script()
        for name, n in self.numbers().items():
            self.assertEqual(n["as_of"], "2026-10-07", name)

    def test_collection_is_incremental(self) -> None:
        self.run_script()
        self.assertNotIn("--search", self.gh_calls()[0])  # the first run collects everything
        self.serve([pr(3, 800, "2026-10-03T10:00:00Z"), pr(4, 50, "2026-10-04T09:00:00Z")])
        self.run_script(today="2026-10-08")
        second = self.gh_calls()[1]
        self.assertEqual(second[second.index("--search") + 1], "merged:>=2026-10-03")
        values = {name: n["value"] for name, n in self.numbers().items()}
        self.assertEqual(values["prs_merged"], 4)  # PR 3 isn't counted twice

    def test_a_number_keeps_its_date_until_it_changes(self) -> None:
        self.run_script()
        self.serve([pr(4, 50, "2026-10-04T09:00:00Z")])
        self.run_script(today="2026-10-08")
        numbers = self.numbers()
        self.assertEqual(numbers["releases"]["as_of"], "2026-10-07")
        self.assertEqual(numbers["prs_merged"]["as_of"], "2026-10-08")

    def test_a_second_run_with_nothing_new_changes_nothing(self) -> None:
        self.run_script()
        site = os.path.join(self.root, "site")
        before = {name: open(os.path.join(site, name)).read() for name in os.listdir(site)}
        result = self.run_script(today="2026-10-09")
        self.assertEqual(result.returncode, 0)
        after = {name: open(os.path.join(site, name)).read() for name in os.listdir(site)}
        self.assertEqual(before, after)
        self.assertIn("nothing changed", result.stdout)

    def test_a_failed_gh_writes_nothing(self) -> None:
        result = self.run_script(FAKE_GH_FAIL="1")
        self.assertEqual(result.returncode, 1)
        self.assertIn("gh", result.stderr)
        self.assertFalse(os.path.exists(os.path.join(self.root, "site")))

    def test_fallback_numbers_in_the_page_are_updated(self) -> None:
        page = os.path.join(self.root, "site", "index.html")
        write(page, '<p><span class="n" data-metric="prs_merged">0</span> PRs, '
                    '<time data-metric-date="prs_merged" datetime="2000-01-01">Jan 1, 2000</time>; '
                    '<span data-metric="prs_within_400">0%</span>; <span data-metric="unknown">keep</span></p>\n')
        self.serve([pr(n, 10 if n % 5 else 900, "2026-10-01T10:00:00Z") for n in range(1, 1201)])
        self.run_script()
        with open(page) as f:
            html = f.read()
        self.assertIn('<span class="n" data-metric="prs_merged">1,200</span>', html)
        self.assertIn('<time data-metric-date="prs_merged" datetime="2026-10-07">Oct 7, 2026</time>', html)
        self.assertIn('<span data-metric="prs_within_400">80%</span>', html)
        self.assertIn('<span data-metric="unknown">keep</span>', html)

    def test_only_public_data_is_read(self) -> None:
        with open(SCRIPT) as f:
            source = f.read()
        for private in ("projects.yaml", "hook-log", "ai-inventory", "ai-tools.json"):
            self.assertNotIn(private, source)

    def test_median_and_share_helpers(self) -> None:
        self.assertEqual(site_metrics.median([5, 1, 3, 2]), 2.5)
        self.assertEqual(site_metrics.median([]), 0)
        self.assertEqual(site_metrics.format_value("prs_within_400", 67), "67%")
        self.assertEqual(site_metrics.format_value("rules_tokens", 30171), "30,171")
        self.assertEqual(site_metrics.format_date("2026-10-07"), "Oct 7, 2026")
        self.assertEqual(site_metrics.format_date(date(2026, 1, 9).isoformat()), "Jan 9, 2026")


if __name__ == "__main__":
    unittest.main()
